crate-head: asd
santa-name: "&cSanta Claus"
santa-skin-name: "faat"

snow-falling:
  enabled: true
  regions: [spawn, nopvp]
  snow-amount: 10
  snow-interval: 10

snowball-fight:
  enabled: true
  regions: [spawn, snowballpvp]
  # Available Placeholders:
  # %nsanta_snowballfight_point%
  points-per-hit: 10

christmas-tree:
  enabled: true
  tree-location:
    world: "world"
    x: 0
    y: 90
    z: 0
  npc-location:
    world: "world"
    x: -6
    y: -16
    z: -52
    yaw: 0
    pitch: 0
    turnYaw: 178
    turnPitch: -1.5
  ingredients:
    - "SPRUCE_LOG:128"
    - "SNOW_BLOCK:100"
    - "REDSTONE_BLOCK:12"
  # everyone / contributors
  reward-players: "everyone"
  complete-rewards:
    - "DIAMOND:5"
  light-settings:
    enabled: true
    particle: "FIREWORKS_SPARK"
    particle-amount: 10
    radius: 5
    rotation-speed: 0.1

advanced-snowman:
  enabled: true
  name: "&b%player%'s Snowman"
  heart: 30
  damage-multiplier: 5
  rewards:
    enabled: true
    money-per-kill: 10.0
    items-per-kill:
      - "DIAMOND:5:%60"
      - "GOLD_INGOT:1:%100"
    monsters:
      - ZOMBIE
      - SKELETON
      - SPIDER
      - CREEPER

christmas-box:
  enabled: true
  #https://minecraft-heads.com
  #1.21+ use Minecraft URL | https://minecraft-heads.com/texture/4b2fcf557b337a2c3a6d5f87756c1eeebada964567661f7320c47871dd5d666
  #1.16-1.20 use Value | eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2YwNzU5ZjQ1MzYxOTU5MDM2YmMxNjIxY2Q5YmE0YmVmYWUzMGVkZjRiNGU5ZmYwMTlhZWMwNzA3NDc2NmFkZiJ9fX0=
  texture: "66a452eb47b943b5240e38235ff77a6865efb9335bfb1ba93e1dd8f7e6e9f589"
  worlds: [world]
  regions: [spawn]
  rewards:
    - "DIAMOND:5:%10"
    - "GOLD_INGOT:1:%10"
    - "IRON_INGOT:1:%10"
    - "EMERALD:1:%10"
    - "GOLDEN_APPLE:1:%5"